### ISSUE TITLE
ubuntu 安装失败

### ISSUE THREAD

**Issue by Thulof** [HSEFZ/bbq#2]
在git clone步骤的时候，由于速度过慢。以及本机已有NodeJS，所以跳过了。
之后拷贝源代码，在执行npm install的时候卡在  (node-gyp rebuild 2> builderror.log) || (exit 0)
如果执行npm install node-gyp的话可以安装成功 但是npm start会报错。

平台 ubuntu 腾讯云服务器

**Comment by jcpwfloi** [comment]
plz use English on GitHub

It seems that you haven't installed node-gyp.

You can install it by typing

```
npm i -g node-gyp
```

then remove the node_modules & npm install:

```
rm -r node_modules; npm i
```

It's all done now!

**Comment by Thulof** [comment]
ok..
Now , I have installed all of them.
However , it don't work.
I think there may be some config that should be change. For example the path of website . My default path is /usr/share/nginx/html

发送自我的三星设备

-------- 原始邮件 --------
发件人： David Chen notifications@github.com
日期: 28-01-2016 23:17 (GMT+08:00)
收件人： HSEFZ/bbq bbq@noreply.github.com
抄送： Thulof Qu vn-group@live.com
主题： Re: [bbq] ubuntu 安装失败 (#2)

plz use English on GitHub

It seems that you haven't installed node-gyp.

You can install it by typing

npm i -g node-gyp

then remove the node_modules & npm install:

rm -r node_modules; npm i

It's all done now!

―

**Comment by jcpwfloi** [comment]
It doesn't work through nginx.

It starts on a dedicated port on http://YOUR_IP:3000.

If you solely want to visit it through nginx you can write proxy configurations in nginx.

**Comment by Thulof** [comment]
Thank you.
It can be visited now.
However , when I post a new message , the web will crash. and the server print so many ERR like this.
Thank you very much for support.
It's very kind of you.

发送自我的三星设备
-------- 原始邮件 --------
发件人： David Chen notifications@github.com
日期: 28-01-2016 23:31 (GMT+08:00)
收件人： HSEFZ/bbq bbq@noreply.github.com
抄送： Thulof Qu vn-group@live.com
主题： Re: [bbq] ubuntu 安装失败 (#2)

It doesn't work through nginx.

It starts on a dedicated port on http://YOUR_IP:3000.

If you solely want to visit it through nginx you can write proxy configurations in nginx.

―

**Comment by jcpwfloi** [comment]
You should set a core value via mongo.

Enter mongo in the terminal to connect, then

```
use bbq
db.core.insert({name: 'total', value: 0});
```

It's done!

This issue will be fixed in the next version with installation script.

**Comment by Thulof** [comment]
It work! Thank you very much!!!!!!!!!
It's very awesome!!
So Cool!!
Could you provide your alipay accont?
I want give you a gift.
Thank you.

发送自我的三星设备

-------- 原始邮件 --------
发件人： David Chen notifications@github.com
日期: 28-01-2016 23:31 (GMT+08:00)
收件人： HSEFZ/bbq bbq@noreply.github.com
抄送： Thulof Qu vn-group@live.com
主题： Re: [bbq] ubuntu 安装失败 (#2)

It doesn't work through nginx.

It starts on a dedicated port on http://YOUR_IP:3000.

If you solely want to visit it through nginx you can write proxy configurations in nginx.

―

**Comment by jcpwfloi** [comment]
alipay: czr8815@hotmail.com

You're welcome, please keep track of the update of version 2 and feel free to report bugs.

**Comment by Thulof** [comment]
Thank you very much.
It's cool

发送自我的三星设备

-------- 原始邮件 --------
发件人： David Chen notifications@github.com
日期: 28-01-2016 23:54 (GMT+08:00)
收件人： HSEFZ/bbq bbq@noreply.github.com
抄送： Thulof Qu vn-group@live.com
主题： Re: [bbq] ubuntu 安装失败 (#2)

alipay: czr8815@hotmail.commailto:czr8815@hotmail.com

You're welcome, please keep track of the update of version 2 and feel free to report bugs.

―
